/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF, useTexture } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";

export function Frame(props: ThreeElements["group"]) {
    const { nodes, materials } = useGLTF("/frame.glb") as any;
    const texture = useTexture("/patrick.png");

    return (
        <group {...props} dispose={null}>
            <group position={[-1.894, 3.089, -1.524]} scale={0.387}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_1.geometry}
                    material={materials["Material.001"]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Cube002_2.geometry}
                    rotation={[0, 0, Math.PI]}
                >
                    <meshStandardMaterial map={texture} />
                </mesh>
            </group>
        </group>
    );
}

useGLTF.preload("/frame.glb");
