/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useState, useEffect } from "react";
import { useGLTF, Text3D, Center } from "@react-three/drei";
import { ThreeElements } from "@react-three/fiber";

export function Mailbox(props: ThreeElements["group"]) {
    const { nodes, materials } = useGLTF("/mailbox.glb") as any;
    const [hovered, setHovered] = useState(false);

    useEffect(() => {
        document.body.style.cursor = hovered ? "pointer" : "auto";
    }, [hovered]);

    return (
        <group
            {...props}
            dispose={null}
            onPointerOver={() => setHovered(true)}
            onPointerOut={() => setHovered(false)}
        >
            <Center position={[0.5, 2.5, 4.557]}>
                <Text3D
                    font="/geist-mono-regular-font.json"
                    size={0.2}
                    height={0.05}
                >
                    Click for email
                    <meshStandardMaterial color="yellow" />
                </Text3D>
            </Center>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.mailbox002.geometry}
                material={materials["tiny_treats_1.002"]}
                position={[0, 0, 4.557]}
            >
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mailbox_door002.geometry}
                    material={materials["tiny_treats_1.002"]}
                    position={[0, 1, 0.8]}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.mailbox_flag002.geometry}
                    material={materials["tiny_treats_1.002"]}
                    position={[0.238, 1.39, 0.68]}
                />
            </mesh>
        </group>
    );
}

useGLTF.preload("/mailbox.glb");
